name: shader
description: Command-line application for compiling GLSL shaders into Flutter-compatible SPR-V byte code.
version: 1.0.0
homepage: https://github.com/felixblaschke/shader

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  http: ^0.13.4
  path: ^1.8.2
  stringr: ^1.0.0
  watcher: ^1.0.1

dev_dependencies:
  lints: ^2.0.0

executables:
  shader: shader
